basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [path("", views.basket_summary, name="basket_summary")]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("products", views.products_all, name="products_all"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
    path("shop/<slug:category_slug>", views.category_detail, name="category_detail"),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("store:category_detail", args=[self.slug])

    def __str__(self) -> str:
        return self.name


class ProductManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super(ProductManager, self).get_queryset().filter(published=True)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="product", on_delete=models.PROTECT
    )
    created_by = models.ForeignKey(
        User, related_name="product_creator", on_delete=models.PROTECT
    )

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    quantity = models.IntegerField(default=0)
    min_stock_level = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)

    weight_in_kgs = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    weight_in_grams = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )

    volume_in_millilitres = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    volume_in_litres = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    volume_in_centilitres = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )

    is_pack = models.BooleanField(blank=True, null=True)
    is_pouch = models.BooleanField(blank=True, null=True)
    is_bottle = models.BooleanField(blank=True, null=True)
    is_container = models.BooleanField(blank=True, null=True)

    published = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    image = models.ImageField(upload_to="images/", default="images/default.jpg")

    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "products"
        ordering = ("-created_at",)

    def __str__(self) -> str:
        return f"{self.title} ({self.size}{self.size_unit})"

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    @property
    def size(self):
        if self.weight_in_grams:
            return self.weight_in_grams
        if self.weight_in_kgs:
            return self.weight_in_kgs
        if self.volume_in_litres:
            return self.volume_in_litres
        if self.volume_in_millilitres:
            return self.volume_in_millilitres
        if self.volume_in_centilitres:
            return self.volume_in_centilitres

    @property
    def size_unit(self):
        if self.weight_in_grams:
            return "g"
        if self.weight_in_kgs:
            return "kg"
        if self.volume_in_litres:
            return "l"
        if self.volume_in_millilitres:
            return "ml"
        if self.volume_in_centilitres:
            return "cl"

basket/views.py
from django.shortcuts import render


def basket_summary(request):
    return render(request, "store/basket/summary.html")

store/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def index(request):
    all_products = Product.products.all()

    return render(
        request,
        "store/index.html",
        {
            "products": all_products,
        },
    )


def products_all(request):
    products = Product.products.all()

    return render(
        request,
        "store/products/products.html",
        {
            "products": products,
        },
    )


def category_detail(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)

    return render(
        request,
        "store/categories/category.html",
        {"category": category, "products": products},
    )


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, published=True)

    return render(
        request,
        "store/products/product.html",
        {
            "product": product,
        },
    )

store/templates/store/basket/summary.html
{% extends "store/layout/layout.html" %}
{% load static %}

{% block title %} Basket Summary {% endblock  %}

{% block body %}
  <h1>
    SOLID
  </h1>
{% endblock  %}

store/templates/store/categories/category.html
{% extends "store/layout/layout.html" %}

{% block title %}
  {{ category.name }}
{% endblock  %}

{% block body %}
  <h1>
    {{ category.name }}
  </h1>

  {% include "store/products/products_list.html" %}
{% endblock  %}

store/templates/store/category.html
{% extends "store/layout.html" %}

{% block title %}
  {{ category.name }}
{% endblock  %}

{% block body %}
  <h1>
    {{ category.name }}
  </h1>

  {% include "store/products_list.html" %}
{% endblock  %}

store/templates/store/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="/">
      <ion-icon name="home-outline" size="large"></ion-icon>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 250px;">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:products' %}">Products</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <div class="container" style="width: 650px">
              <div class="row">
                {% for category in categories %}
                  <div class="col-4">
                    <li><a class="dropdown-item py-1" href="{{ category.get_absolute_url }}">
                      {{ category | title }}
                    </a></li>
                  </div>
                {% endfor %}
              </div>
            </div>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

store/templates/store/index.html
{% extends "store/layout/layout.html" %}

{% block title %}
  Healthy living
{% endblock  %}

{% block body %}
  <div class="p-5 mb-4 rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Healthy foods and oils</h1>
      <p class="col-md-8 fs-4">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam esse mollitia illo reiciendis cumque eius laboriosam? Eligendi eum, ipsam dolores id sint distinctio nihil?
      </p>
      <button class="btn btn-primary btn-lg" type="button">Place an order</button>
    </div>
  </div>

  {% include "store/products/products_list.html" %}
{% endblock  %}

store/templates/store/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link href="{% static 'store/css/styles.css' %}" rel="stylesheet">

  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

  <title>
    GF Store |  {% block title %} Healthy living {% endblock  %}
  </title>
</head>
<body>
  {% include "store/header.html" %}

  <div id="content" class="container" style="padding-bottom: 125px">
    {% block body %}

    {% endblock  %}
  </div>

  <div class="container" style="margin-top: 35px">
    {% include "store/footer.html" %}
  </div>
</body>
</html>

store/templates/store/layout/footer.html
<footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
  <div class="col mb-3">
    <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>
    <p class="text-body-secondary">© 2023</p>
  </div>

  <div class="col mb-3">

  </div>

  <div class="col mb-3">
    <h5>Section</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
    </ul>
  </div>

  <div class="col mb-3">
    <h5>Section</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
    </ul>
  </div>

  <div class="col mb-3">
    <h5>Section</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
      <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
    </ul>
  </div>
</footer>

store/templates/store/layout/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="/">
      <ion-icon name="home-outline" size="large"></ion-icon>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 250px;">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:products_all' %}">Products</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <div class="container" style="width: 650px">
              <div class="row">
                {% for category in categories %}
                  <div class="col-4">
                    <li><a class="dropdown-item py-1" href="{{ category.get_absolute_url }}">
                      {{ category | title }}
                    </a></li>
                  </div>
                {% endfor %}
              </div>
            </div>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <a class="basket ms-3" href="{% url 'basket:basket_summary' %}">
      <ion-icon name="basket-outline" size="large"></ion-icon>
      <span> 1 </span>
    </a>
  </div>
</nav>

store/templates/store/layout/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link href="{% static 'store/css/styles.css' %}" rel="stylesheet">

  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

  <script src="{% static 'store/js/main.js' %}"></script>

  <title>
    GF Store |  {% block title %} Healthy living {% endblock  %}
  </title>
</head>
<body>
  {% include "store/layout/header.html" %}

  <div id="content" class="container" style="padding-bottom: 125px">
    {% block body %}

    {% endblock  %}
  </div>

  {% comment %} <div class="container" style="margin-top: 35px">
    {% include "store/layout/footer.html" %}
  </div> {% endcomment %}
</body>
</html>

store/templates/store/product.html
{% extends "store/layout.html" %}

{% block title %}
  {{ product.title }}
{% endblock  %}

{% block body %}
  <div class="row">
    <div class="col-lg-5 mt-5">
      <div class="card mb-3">
        <img class="card-img img-fluid" src="{{ product.image.url }}" alt="Card image cap" id="product-detail">
      </div>
    </div>
    <!-- col end -->
    <div class="col-lg-7 mt-5">
      <div class="card">
        <div class="card-body">
          <h1 class="h2">{{ product }}</h1>
          <p class="h3 py-2">NGN{{ product.price }}</p>
          <p class="py-2">
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-secondary"></i>
            <span class="list-inline-item text-dark">Rating 4.8 | 36 Comments</span>
          </p>
          <ul class="list-inline">
            <li class="list-inline-item">
              <h6>Category:</h6>
            </li>
            <li class="list-inline-item">
              <p class="text-muted"><strong>{{ product.category }}</strong></p>
            </li>
          </ul>

          <h6>Description:</h6>
          <p>
            {{ product.description }}
          </p>

          {% comment %} <ul class="list-inline">
            <li class="list-inline-item">
              <h6>Avaliable Color :</h6>
            </li>
            <li class="list-inline-item">
              <p class="text-muted"><strong>White / Black</strong></p>
            </li>
          </ul> {% endcomment %}

          {% comment %} <h6>Specification:</h6>
          <ul class="list-unstyled pb-3">
            <li>Lorem ipsum dolor sit</li>
            <li>Amet, consectetur</li>
            <li>Adipiscing elit,set</li>
            <li>Duis aute irure</li>
            <li>Ut enim ad minim</li>
            <li>Dolore magna aliqua</li>
            <li>Excepteur sint</li>
          </ul> {% endcomment %}

          <form action="" method="GET">
            <input type="hidden" name="product-title" value="Activewear">
            <div class="row">
              {% comment %} <div class="col-auto">
                <ul class="list-inline pb-3">
                  <li class="list-inline-item">Size :
                    <input type="hidden" name="product-size" id="product-size" value="S">
                  </li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">S</span></li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">M</span></li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">L</span></li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">XL</span></li>
                </ul>
              </div> {% endcomment %}
              <div class="col-auto">
                <ul class="list-inline pb-3">
                  <li class="list-inline-item text-right">
                    Quantity
                    <input type="hidden" name="product-quanity" id="product-quanity" value="1">
                  </li>
                  <li class="list-inline-item"><span class="btn btn-success" id="btn-minus">-</span></li>
                  <li class="list-inline-item"><span class="badge bg-secondary" id="var-value">1</span></li>
                  <li class="list-inline-item"><span class="btn btn-success" id="btn-plus">+</span></li>
                </ul>
              </div>
            </div>
            <div class="row pb-3">
              {% comment %} <div class="col d-grid">
                <button type="submit" class="btn btn-success btn-lg" name="submit" value="buy">Buy</button>
              </div> {% endcomment %}
              <div class="col d-grid">
                <button type="submit" class="btn btn-success btn-lg" name="submit" value="addtocard">Add To Cart</button>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

  {{ product }}
{% endblock  %}

store/templates/store/products.html
{% extends "store/layout.html" %}

{% block title %}
  All Products
{% endblock  %}

{% block body %}
  <div class="my-4">
    <h1>
      All Products
    </h1>
    {% include "store/products_list.html" %}
  </div>
{% endblock  %}

store/templates/store/products/product.html
{% extends "store/layout/layout.html" %}

{% block title %}
  {{ product.title }}
{% endblock  %}

{% block body %}
  <div class="row">
    <div class="col-lg-5 mt-5">
      <div class="card mb-3">
        <img class="card-img img-fluid" src="{{ product.image.url }}" alt="Card image cap" id="product-detail">
      </div>
    </div>
    <!-- col end -->
    <div class="col-lg-7 mt-5">
      <div class="card">
        <div class="card-body">
          <h1 class="h2">{{ product }}</h1>
          <p class="h3 py-2">NGN{{ product.price }}</p>
          <p class="py-2">
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-warning"></i>
            <i class="fa fa-star text-secondary"></i>
            <span class="list-inline-item text-dark">Rating 4.8 | 36 Comments</span>
          </p>
          <ul class="list-inline">
            <li class="list-inline-item">
              <h6>Category:</h6>
            </li>
            <li class="list-inline-item">
              <p class="text-muted"><strong>{{ product.category }}</strong></p>
            </li>
          </ul>

          <h6>Description:</h6>
          <p>
            {{ product.description }}
          </p>

          {% comment %} <ul class="list-inline">
            <li class="list-inline-item">
              <h6>Avaliable Color :</h6>
            </li>
            <li class="list-inline-item">
              <p class="text-muted"><strong>White / Black</strong></p>
            </li>
          </ul> {% endcomment %}

          {% comment %} <h6>Specification:</h6>
          <ul class="list-unstyled pb-3">
            <li>Lorem ipsum dolor sit</li>
            <li>Amet, consectetur</li>
            <li>Adipiscing elit,set</li>
            <li>Duis aute irure</li>
            <li>Ut enim ad minim</li>
            <li>Dolore magna aliqua</li>
            <li>Excepteur sint</li>
          </ul> {% endcomment %}

          <form action="" method="GET">
            <input type="hidden" name="product-title" value="Activewear">
            <div class="row">
              {% comment %} <div class="col-auto">
                <ul class="list-inline pb-3">
                  <li class="list-inline-item">Size :
                    <input type="hidden" name="product-size" id="product-size" value="S">
                  </li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">S</span></li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">M</span></li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">L</span></li>
                  <li class="list-inline-item"><span class="btn btn-success btn-size">XL</span></li>
                </ul>
              </div> {% endcomment %}
              <div class="col-auto">
                <ul class="list-inline pb-3">
                  <li class="list-inline-item text-right">
                    Quantity
                    <input type="hidden" name="product-quanity" id="product-quanity" value="1">
                  </li>
                  <li class="list-inline-item"><span class="btn btn-success" id="btn-minus">-</span></li>
                  <li class="list-inline-item"><span class="badge bg-secondary" id="var-value">1</span></li>
                  <li class="list-inline-item"><span class="btn btn-success" id="btn-plus">+</span></li>
                </ul>
              </div>
            </div>
            <div class="row pb-3">
              {% comment %} <div class="col d-grid">
                <button type="submit" class="btn btn-success btn-lg" name="submit" value="buy">Buy</button>
              </div> {% endcomment %}
              <div class="col d-grid">
                <button type="submit" class="btn btn-success btn-lg" name="submit" value="addtocard">Add To Cart</button>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

  {{ product }}
{% endblock  %}

store/templates/store/products/products.html
{% extends "store/layout/layout.html" %}

{% block title %}
  All Products
{% endblock  %}

{% block body %}
  <div class="my-4">
    <h1>
      All Products
    </h1>
    {% include "store/products/products_list.html" %}
  </div>
{% endblock  %}

store/templates/store/products/products_list.html
<div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 g-3">
  {% for product in products %}
    <div class="col-12 col-sm-12 col-md-6 col-lg-4">
      <div class="card shadow-sm">
        <img src="{{ product.image.url }}" style="object-fit: cover; height: 300px" alt="">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{{ product.get_absolute_url }}">
              {{ product }}
            </a>
          </h5>
          <p class="card-text">
            {{ product.description | truncatechars:150 }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Add to cart
              </button>
              <button type="button" class="btn btn-sm btn-outline-secondary flex items-center justify-center">
                <ion-icon name="heart-outline" style="font-size: 1.6em; margin-top: 3px"></ion-icon>
              </button>
            </div>
            <h6 class="text-success text-bold">
              <strong>
                NGN{{ product.price }}
              </strong>
            </h6>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

store/templates/store/products_list.html
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  {% for product in products %}
    <div class="col-4">
      <div class="card shadow-sm">
        <img src="{{ product.image.url }}" style="object-fit: cover; height: 300px" alt="">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{{ product.get_absolute_url }}">
              {{ product }}
            </a>
          </h5>
          <p class="card-text">
            {{ product.description | truncatechars:150 }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Add to cart
              </button>
              <button type="button" class="btn btn-sm btn-outline-secondary flex items-center justify-center">
                <ion-icon name="heart-outline" style="font-size: 1.6em; margin-top: 3px"></ion-icon>
              </button>
            </div>
            <h6 class="text-success text-bold">
              <strong>
                NGN{{ product.price }}
              </strong>
            </h6>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>